### PR TITLE
Cache links per-client instance, not globally

### PR DESCRIPTION
**Pull request by dnwe**
By default the link cache was being built-up globally and the hash is
only based upon the type, address and options, and not tied to the
Client. This was problematic if multiple Client objects are created
within the same node instance.

### CODE REVIEW

**Comment by mbroadst** [comment]
@dnwe Thanks for the contribution! I'm seeing some jshint errors related to strictness violations, as well as 4 failed integration tests, any way you could clean that up?

**Comment by mbroadst** [comment]
it looks like the strictness errors could be resolved simply by passing `self` to the methods, instead of `apply`ing and using `this`

**Comment by dnwe** [comment]
Will do. I struggled to get the dev deps installed on my Debian box with node 6. I'll try again in a docker container.

**Comment by mbroadst** [comment]
you should be able to test pretty easily if you have qpidd running with `auth=no` configured. Then it should be as easy as `npm install && SERVER=<ip of qpidd> make test`

**Comment by mbroadst** [comment]
@dnwe also out of morbid curiosity, can you explain the decision to use more `apply`, as well as `{}.hasOwnProperty.call`? Just interested in whether there's some secret juju I'm missing here 😄

**Comment by dnwe** [comment]
@mbroadst updated commit attached (b6b102e), tbh the `.apply(self, [args])` pattern was just what I wrote on a 1st pass, trying to preserve 'this' within prototype calls, but you're right its probably better to just pass the client in as an explicit argument instead. The `{}.hasOwnProperty.call` pattern is just a force of habit from satisfying [no-prototype-builtins](http://eslint.org/docs/rules/no-prototype-builtins) to silence eslint.

**Comment by mbroadst** [comment]
@dnwe great, thanks! I'll add some tests

**Pull request merged**
